### ISSUE TITLE
rtfm-rs org TODO list

### ISSUE THREAD

**Issue by japaric** [rtic-rs/cortex-m-rtic#233]
- [x] move repos from japaric/ to rtfm-rs/
- [x] add CONTRIBUTING.md to this repo indicating that the rfcs repo is for RFCs and new features should be discussed there before opening a PR here
- [x] rtfm-rs README needs updating
- [x] the README in this repo (and thus the book) should point to the rfcs repository
- [x] the README in this repo (and thus the book) should point to the matrix channel
- [ ] add issue template indicating that this repo is for bug reports and that features should be discussed in the rfcs repository
- [x] get gh-pages working again (@japaric)  #234 
- [x] update Cargo.toml metadata in all repos to point to rtfm-rs/* URLs
 - [x] migrate feature related issues from this repo to the rfcs repo

**Comment by korken89** [comment]
Check licenses as well
